apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserv
  #namespace: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      name: myhello
      labels:
        app: web-app
    spec:
      containers:
        - name: myhello
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pn-config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pn-config
          configMap:
            name: nginx-piano