apiVersion: v1
kind: Service
metadata:
  name: nginx-project
  #namespace: test2
spec:
  type: ClusterIP
  ports:
    - port: 80
      #nodePort: 30006
      targetPort: 80
  selector:
    app: web-app