apiVersion: v1
kind: Service
metadata:
  name: oatnginx-project
  #namespace: test2
spec:
  type: ClusterIP
  ports:
    - port: 80
      #nodePort: 32000
      targetPort: 80
  selector:
    app: oatweb-app